### ISSUE TITLE
The sourcePath can be empty if the files are in the bucket path

### ISSUE THREAD

**Issue by userlab-alejandravelasquez** [Wolfsin/aws-s3-archiver#3]
If the files I need to use are in the s3 path, I cannot access them because there is a validation that the sourcePath is not empty.

and I can't place only / because the code automatically adds it to the image path.

**Comment by Wolfsin** [comment]
Thanks for raising the issue, I will check & fix it ASAP.
Before I do this I want to confirm, you mean you want to use it at the root of a bucket, right?
For example, you have a test bucket, and your operation object is sample.txt, so the full path is /sample.txt, right?

**Comment by Wolfsin** [comment]
@userlab-alejandravelasquez 
Thank you for your cooperation.
The new version 1.0.3 has been released and solved the problem.
